N0 :Person name:"N0"   age:10 location:"Chile"
N1 :Person name:"N1"   age:30 location:"Chile"
N2 :Person name:"N2"   age:29 location:"Philippines"
N3 :Person name:"N3"   age:23 location:"Russia"
N4 :Person name:"N4"   age:36 location:"Argentina"
N5 :Person name:"N5"   age:73 location:"Russia"
N6 :Person name:"N6"   age:62 location:"China"
N7 :Person name:"N7"   age:56 location:"Honduras"
N8 :Person name:"N8"   age:54 location:"Italy"
N9 :Person name:"N9"   age:12 location:"China"
N10 :Person name:"N10" age:76 location:"China"
N11 :Person name:"N11" age:16 location:"China"
N12 :Person name:"N12" age:26 location:"Germany"
N13 :Person name:"N13" age:77 location:"Germany"
N14 :Person name:"N14" age:40 location:"Italy"
B6 :Book name:"B6"
B7 :Book name:"B7"
B8 :Book name:"B8"
B9 :Book name:"B9"
B10 :Book name:"B10"
N0->N1 :Follows name:"F0"
N0->N2 :Follows name:"F1"
N1->N3 :Follows name:"F2"
N1->N4 :Follows name:"F3"
N2->N0 :Follows name:"F4"
N2->N3 :Follows name:"F5"
N2->N5 :Follows name:"F6"
N3->N4 :Follows name:"F7"
N4->N1 :Follows name:"F8"
N0->B9 :Owns name:"O9"
N1->B9 :Owns name:"O10"
N2->B6 :Owns name:"O11"
N2->B7 :Owns name:"O12"
N2->B8 :Owns name:"O13"
N3->B7 :Owns name:"O14"
N4->B6 :Owns name:"O15"
N4->B8 :Owns name:"O16"
