#pragma once

#include "query/exceptions.h"

namespace GQL {
class OpFilter;
class ExprAnd;
class ExprOr;
class ExprNot;
class ExprHasNodeLabel;
class ExprHasEdgeLabel;
class ExprWildcardLabel;
class ExprEquals;
class ExprVar;
class ExprProperty;
class ExprConcat;
class ExprGreaterOrEquals;
class ExprGreater;
class ExprIs;
class ExprLessOrEquals;
class ExprNotEquals;
class ExprLess;
class ExprLess;
class ExprXor;
class ExprTerm;
class ExprAddition;
class ExprSubtraction;
class ExprMultiplication;
class ExprDivision;
class ExprAbs;
class ExprModulo;
class ExprSin;
class ExprCos;
class ExprTan;
class ExprCot;
class ExprSinh;
class ExprCosh;
class ExprTanh;
class ExprAsin;
class ExprAcos;
class ExprAtan;
class ExprDegrees;
class ExprRadians;
class ExprLog;
class ExprLog10;
class ExprLn;
class ExprExp;
class ExprPower;
class ExprSqrt;
class ExprFloor;
class ExprCeil;
class ExprLength;
class ExprSubStr;
class ExprFold;
class ExprSingleTrim;
class ExprMultiTrim;
class ExprNormalize;
class ExprNullIf;
class ExprCoalesce;
class ExprSimpleCase;
class ExprSearchedCase;
class ExprCast;

class ExprAggCountAll;
class ExprAggCount;
class ExprAggAvg;
class ExprAggMax;
class ExprAggMin;
class ExprAggSum;
class ExprAggStddevPop;
class ExprAggStddevSamp;
class ExprAggCollect;
class ExprAggPercentileCont;
class ExprAggPercentileDisc;

class ExprVisitor {
public:
    virtual ~ExprVisitor() = default;

    // GQL
    virtual void visit(GQL::ExprAnd&) = 0;
    virtual void visit(GQL::ExprOr&) = 0;
    virtual void visit(GQL::ExprNot&) = 0;
    virtual void visit(GQL::ExprHasNodeLabel&) = 0;
    virtual void visit(GQL::ExprHasEdgeLabel&) = 0;
    virtual void visit(GQL::ExprWildcardLabel&) = 0;
    virtual void visit(GQL::ExprEquals&) = 0;
    virtual void visit(GQL::ExprVar&) = 0;
    virtual void visit(GQL::ExprProperty&) = 0;
    virtual void visit(GQL::ExprXor&) = 0;
    virtual void visit(GQL::ExprConcat&) = 0;
    virtual void visit(GQL::ExprGreaterOrEquals&) = 0;
    virtual void visit(GQL::ExprGreater&) = 0;
    virtual void visit(GQL::ExprIs&) = 0;
    virtual void visit(GQL::ExprLessOrEquals&) = 0;
    virtual void visit(GQL::ExprLess&) = 0;
    virtual void visit(GQL::ExprNotEquals&) = 0;
    virtual void visit(GQL::ExprTerm&) = 0;
    virtual void visit(GQL::ExprAddition&) = 0;
    virtual void visit(GQL::ExprSubtraction&) = 0;
    virtual void visit(GQL::ExprMultiplication&) = 0;
    virtual void visit(GQL::ExprDivision&) = 0;
    virtual void visit(GQL::ExprAbs&) = 0;
    virtual void visit(GQL::ExprModulo&) = 0;
    virtual void visit(GQL::ExprSin&) = 0;
    virtual void visit(GQL::ExprCos&) = 0;
    virtual void visit(GQL::ExprTan&) = 0;
    virtual void visit(GQL::ExprCot&) = 0;
    virtual void visit(GQL::ExprSinh&) = 0;
    virtual void visit(GQL::ExprCosh&) = 0;
    virtual void visit(GQL::ExprTanh&) = 0;
    virtual void visit(GQL::ExprAsin&) = 0;
    virtual void visit(GQL::ExprAcos&) = 0;
    virtual void visit(GQL::ExprAtan&) = 0;
    virtual void visit(GQL::ExprDegrees&) = 0;
    virtual void visit(GQL::ExprRadians&) = 0;
    virtual void visit(GQL::ExprLog&) = 0;
    virtual void visit(GQL::ExprLog10&) = 0;
    virtual void visit(GQL::ExprLn&) = 0;
    virtual void visit(GQL::ExprExp&) = 0;
    virtual void visit(GQL::ExprPower&) = 0;
    virtual void visit(GQL::ExprSqrt&) = 0;
    virtual void visit(GQL::ExprFloor&) = 0;
    virtual void visit(GQL::ExprCeil&) = 0;
    virtual void visit(GQL::ExprLength&) = 0;
    virtual void visit(GQL::ExprSubStr&) = 0;
    virtual void visit(GQL::ExprFold&) = 0;
    virtual void visit(GQL::ExprSingleTrim&) = 0;
    virtual void visit(GQL::ExprMultiTrim&) = 0;
    virtual void visit(GQL::ExprNormalize&) = 0;
    virtual void visit(GQL::ExprNullIf&) = 0;
    virtual void visit(GQL::ExprCoalesce&) = 0;
    virtual void visit(GQL::ExprSimpleCase&) = 0;
    virtual void visit(GQL::ExprSearchedCase&) = 0;
    virtual void visit(GQL::ExprCast&) = 0;
    virtual void visit(GQL::ExprAggCountAll&) = 0;
    virtual void visit(GQL::ExprAggCount&) = 0;
    virtual void visit(GQL::ExprAggAvg&) = 0;
    virtual void visit(GQL::ExprAggMax&) = 0;
    virtual void visit(GQL::ExprAggMin&) = 0;
    virtual void visit(GQL::ExprAggSum&) = 0;
    virtual void visit(GQL::ExprAggStddevPop&) = 0;
    virtual void visit(GQL::ExprAggStddevSamp&) = 0;
    virtual void visit(GQL::ExprAggCollect&) = 0;
    virtual void visit(GQL::ExprAggPercentileCont&) = 0;
    virtual void visit(GQL::ExprAggPercentileDisc&) = 0;
};
} // namespace GQL
