#pragma once

#include <iostream>

#include "antlr4-runtime.h"

#include "parser/query/grammar/mdb/autogenerated/MDBLexer.h"
#include "parser/query/grammar/mdb/autogenerated/MDBParser.h"
#include "parser/query/grammar/mdb/query_visitor.h"
#include "parser/query/op/mdb/op_visitor/check_var_names.h"
#include "parser/query/op/mdb/op_visitor/check_well_designed.h"
#include "parser/query/op/mdb/op_visitor/optimize_optional_tree.h"
#include "parser/query/op/op.h"

namespace MDB {

class QueryParser {
public:
    static std::unique_ptr<Op>
      get_query_plan(const std::string& query, antlr4::ANTLRErrorListener* error_listener = nullptr) {
        antlr4::ANTLRInputStream  input(query);
        MDBLexer                  lexer(&input);
        antlr4::CommonTokenStream tokens(&lexer);
        MDBParser                 parser(&tokens);

        parser.getInterpreter<antlr4::atn::ParserATNSimulator>()->setPredictionMode(antlr4::atn::PredictionMode::SLL);

        if (error_listener != nullptr) {
            parser.removeErrorListeners();
            parser.addErrorListener(error_listener);
        }
        MDBParser::RootContext* tree = parser.root();
        QueryVisitor            visitor;
        visitor.visitRoot(tree);

        auto res = std::move(visitor.current_op);

        std::cout << *res << "\n";

        CheckVarNames check_var_names;
        res->accept_visitor(check_var_names);

        CheckWellDesigned check_well_designed;
        res->accept_visitor(check_well_designed);

        OptimizeOptionalTree optimize_optional_tree;
        res->accept_visitor(optimize_optional_tree);

        return res;
    }
};
} // namespace MDB