#!/usr/bin/bash
set -e

[[ -z "$1" ]] && echo "Missing database file path" && exit 1

[[ ! -f "$1" ]] && echo "Database file does not exist" && exit 1

echo Configure build
cmake -Bbuild/Debug -DCMAKE_BUILD_TYPE=Debug

echo Build
cmake --build build/Debug/ -j $(($(getconf _NPROCESSORS_ONLN)-1))

# Remove tmp dir
[[ -d tests/mql/tmp/ ]] && echo Remove tests/mql/tmp/ && rm -r tests/mql/tmp/

echo Create database
build/Debug/bin/create_db_mql "$1" tests/mql/tmp/dbs/interactive

echo Run server
build/Debug/bin/server_mql --timeout 3600 tests/mql/tmp/dbs/interactive
