#pragma once

#include "agg_avg.h"
#include "agg_avg_distinct.h"
#include "agg_count.h"
#include "agg_count_all.h"
#include "agg_count_all_distinct.h"
#include "agg_count_distinct.h"
#include "agg_group_concat.h"
#include "agg_group_concat_distinct.h"
#include "agg_max.h"
#include "agg_min.h"
#include "agg_sample.h"
#include "agg_sum.h"
#include "agg_sum_distinct.h"
