N0 name:"0"
N1 name:"1"
N2 name:"2"
N3 name:"3"
N0~N1 :people :friends name:"01"
N3~N1 :people :friends name:"02"
N0->N2 :people :follows name:"02"
N0->N1 :people :follows name:"01"
N0<-N1 :people :follows name:"10"
F4 name:"4"
F5 name:"5"
F6 name:"6"
F7 name:"7"
F4->F5 :lookup_table test:"A"
F7~F6 :lookup_table test:"B"
