PREFIX : <http://www.firstPrefix.com/>
SELECT *
WHERE {
    :subjectFirstPrefix :predicateFirstPrefix ?o .
    FILTER (true
        && CEIL(-2.5e0) = -2
        && CEIL(-2.5) = -2

        && CEIL(0.4) = 1
        && CEIL(0.5) = 1
        && CEIL(0.51) = 1
        && CEIL(0.6) = 1
        && CEIL(10.4) = 11
        && CEIL(10.5) = 11
        && CEIL(10.51) = 11
        && CEIL(10.6) = 11

        && CEIL(-0.4) = 0
        && CEIL(-0.5) = 0
        && CEIL(-0.51) = 0
        && CEIL(-0.6) = 0
        && CEIL(-10.4) = -10
        && CEIL(-10.5) = -10
        && CEIL(-10.51) = -10
        && CEIL(-10.6) = -10

        && CEIL(0.4e0) = 1
        && CEIL(0.5e0) = 1
        && CEIL(0.51e0) = 1
        && CEIL(0.6e0) = 1
        && CEIL(10.4e0) = 11
        && CEIL(10.5e0) = 11
        && CEIL(10.51e0) = 11
        && CEIL(10.6e0) = 11

        && CEIL(-0.4e0) = 0
        && CEIL(-0.5e0) = 0
        && CEIL(-0.51e0) = 0
        && CEIL(-0.6e0) = 0
        && CEIL(-10.4e0) = -10
        && CEIL(-10.5e0) = -10
        && CEIL(-10.51e0) = -10
        && CEIL(-10.6e0) = -10

        && CEIL(0) = 0
        && CEIL(0.0) = 0
        && CEIL(0e0) = 0

        && CEIL(-0) = 0
        && CEIL(-0.0) = 0
        && CEIL(-0e0) = 0

        && CEIL(1) = 1
        && CEIL(1.0) = 1
        && CEIL(1e0) = 1

        && CEIL(-1) = -1
        && CEIL(-1.0) = -1
        && CEIL(-1e0) = -1

        && CEIL(453.123) = 454
        && CEIL(123456789.123456789) = 123456790
        && CEIL(453.123e0) = 454

        && CEIL(453.523) = 454
        && CEIL(453.523e0) = 454

        && CEIL(-453.123) = -453
        && CEIL(-123456789.123456789) = -123456789
        && CEIL(-453.123e0) = -453

        && CEIL(-453.523) = -453
        && CEIL(-453.523e0) = -453

        && CEIL(0.000213) = 1
        && CEIL(0.00000000000782348734278) = 1
        && CEIL(0.000213e0) = 1

        && CEIL(-0.000213) = 0
        && CEIL(-0.00000000000782348734278) = 0
        && CEIL(-0.000213e0) = 0

        && CEIL(-999.4e0)                = -999
        && CEIL(-999.5e0)                = -999
        && CEIL(-999.6e0)                = -999

        && CEIL(999.4e0)                 = 1000
        && CEIL(999.5e0)                 = 1000
        && CEIL(999.6e0)                 = 1000
    )
}
