PREFIX : <http://www.firstPrefix.com/>
SELECT *
WHERE {
    :subjectFirstPrefix :predicateFirstPrefix ?o .
    FILTER (true
        && 4 / 2 = 2
        && -4 / 2 = -2
        && 4 / -2 = -2

        && 4 / 2e0 = 2
        && -4 / -2e0 = 2
        && 4 / -2e0 = -2
        && 4 / 2e0 = 2e0
        && -4 / -2e0 = 2e0
        && 4 / -2e0 = -2e0

        && 4 / 2.0 = 2
        && -4 / -2.0 = 2
        && 4 / -2.0 = -2
        && 4 / 2.0 = 2.0
        && -4 / -2.0 = 2.0
        && 4 / -2.0 = -2.0


        && 1.0 / 1.0 = 1.0
        && -1.0 / 1.0 = -1.0
        && -1.0 / -1.0 = 1.0
        && 1.0 / -1.0 = -1.0

        && 4.0 / 2e0 = 2
        && 4e0 / 2.0 = 2
        && -4.0 / 2e0 = -2
        && 4e0 / -2.0 = -2
        && -4e0 / -2.0 = 2

        && 4 / 2 = 2.0
        && 360.0 / 9.0 = 40.0
        && -6.0 / 2.0 = -3.0
        && 0.01 / 4.0 = 0.0025
        && 0.01 / 0.0001 = 100.0

        && 1118604.0 / 93217.0 = 12.0
        && 1118604.0 / 12.0 = 93217.0

        && 1e0 / 0e0 = "INF"^^xsd:float
        && 1e0 / -0e0 = "-INF"^^xsd:float
        && -1e0 / 0e0 = "-INF"^^xsd:float
        && -1e0 / -0e0 = "INF"^^xsd:float

        # NaN != NaN
        && !(0e0 / 0e0 = "NaN"^^xsd:float)
        && !(0e0 / -0e0 = "NaN"^^xsd:float)
        && !(-0e0 / 0e0 = "NaN"^^xsd:float)
        && !(-0e0 / -0e0 = "NaN"^^xsd:float)
    )
}
