PREFIX : <http://www.firstPrefix.com/>
SELECT *
WHERE {
    :subjectFirstPrefix :predicateFirstPrefix ?o .
    FILTER(true
        && "s" = "s"
        && "s"@en = "s"@en
        && "s"^^xsd:string = "s"^^xsd:string
        && "asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf" = "asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf"

        && -10 = -1e1
        && "-10.0"^^xsd:decimal = "-1e1"^^xsd:float
        && "-10.0"^^xsd:float = "-10.0"^^xsd:decimal
        && "-10.0"^^xsd:float = "-10"^^xsd:integer

        && !("NaN"^^xsd:float = "NaN"^^xsd:float)
        && !("-INF"^^xsd:float = "INF"^^xsd:float)
        && "INF"^^xsd:float = "INF"^^xsd:float
        && "-INF"^^xsd:float = "-INF"^^xsd:float
        && "-0"^^xsd:float = "0"^^xsd:float

        && 10 = 10
        && 10 = "10"^^xsd:integer
        && 10 = "10"^^xsd:decimal
        && 10 = "10"^^xsd:float
        && 10 = "10"^^xsd:double
        && 10 = 10.0
        && 10 = "10"^^xsd:integer
        && 10 = "10.0"^^xsd:decimal
        && 10 = "10.0"^^xsd:float
        && 10 = "10.0"^^xsd:double
        && 10 = 1e1
        && 10 = "1e1"^^xsd:float
        && 10 = "1e1"^^xsd:double
        && "10"^^xsd:integer = 10
        && "10"^^xsd:integer = "10"^^xsd:integer
        && "10"^^xsd:integer = "10"^^xsd:decimal
        && "10"^^xsd:integer = "10"^^xsd:float
        && "10"^^xsd:integer = "10"^^xsd:double
        && "10"^^xsd:integer = 10.0
        && "10"^^xsd:integer = "10.0"^^xsd:decimal
        && "10"^^xsd:integer = "10.0"^^xsd:float
        && "10"^^xsd:integer = "10.0"^^xsd:double
        && "10"^^xsd:integer = 1e1
        && "10"^^xsd:integer = "1e1"^^xsd:float
        && "10"^^xsd:integer = "1e1"^^xsd:double
        && "10"^^xsd:decimal = 10
        && "10"^^xsd:decimal = "10"^^xsd:integer
        && "10"^^xsd:decimal = "10"^^xsd:decimal
        && "10"^^xsd:decimal = "10"^^xsd:float
        && "10"^^xsd:decimal = "10"^^xsd:double
        && "10"^^xsd:decimal = 10.0
        && "10"^^xsd:decimal = "10"^^xsd:integer
        && "10"^^xsd:decimal = "10.0"^^xsd:decimal
        && "10"^^xsd:decimal = "10.0"^^xsd:float
        && "10"^^xsd:decimal = "10.0"^^xsd:double
        && "10"^^xsd:decimal = 1e1
        && "10"^^xsd:decimal = "1e1"^^xsd:float
        && "10"^^xsd:decimal = "1e1"^^xsd:double
        && "10"^^xsd:float = 10
        && "10"^^xsd:float = "10"^^xsd:integer
        && "10"^^xsd:float = "10"^^xsd:decimal
        && "10"^^xsd:float = "10"^^xsd:float
        && "10"^^xsd:float = "10"^^xsd:double
        && "10"^^xsd:float = 10.0
        && "10"^^xsd:float = "10"^^xsd:integer
        && "10"^^xsd:float = "10.0"^^xsd:decimal
        && "10"^^xsd:float = "10.0"^^xsd:float
        && "10"^^xsd:float = "10.0"^^xsd:double
        && "10"^^xsd:float = 1e1
        && "10"^^xsd:float = "1e1"^^xsd:float
        && "10"^^xsd:float = "1e1"^^xsd:double
        && "10"^^xsd:double = 10
        && "10"^^xsd:double = "10"^^xsd:integer
        && "10"^^xsd:double = "10"^^xsd:decimal
        && "10"^^xsd:double = "10"^^xsd:float
        && "10"^^xsd:double = "10"^^xsd:double
        && "10"^^xsd:double = 10.0
        && "10"^^xsd:double = "10"^^xsd:integer
        && "10"^^xsd:double = "10.0"^^xsd:decimal
        && "10"^^xsd:double = "10.0"^^xsd:float
        && "10"^^xsd:double = "10.0"^^xsd:double
        && "10"^^xsd:double = 1e1
        && "10"^^xsd:double = "1e1"^^xsd:float
        && "10"^^xsd:double = "1e1"^^xsd:double
        && 10.0 = 10
        && 10.0 = "10"^^xsd:integer
        && 10.0 = "10"^^xsd:decimal
        && 10.0 = "10"^^xsd:float
        && 10.0 = "10"^^xsd:double
        && 10.0 = 10.0
        && 10.0 = "10"^^xsd:integer
        && 10.0 = "10.0"^^xsd:decimal
        && 10.0 = "10.0"^^xsd:float
        && 10.0 = "10.0"^^xsd:double
        && 10.0 = 1e1
        && 10.0 = "1e1"^^xsd:float
        && 10.0 = "1e1"^^xsd:double
        && "10.0"^^xsd:decimal = 10
        && "10.0"^^xsd:decimal = "10"^^xsd:integer
        && "10.0"^^xsd:decimal = "10"^^xsd:decimal
        && "10.0"^^xsd:decimal = "10"^^xsd:float
        && "10.0"^^xsd:decimal = "10"^^xsd:double
        && "10.0"^^xsd:decimal = 10.0
        && "10.0"^^xsd:decimal = "10"^^xsd:integer
        && "10.0"^^xsd:decimal = "10.0"^^xsd:decimal
        && "10.0"^^xsd:decimal = "10.0"^^xsd:float
        && "10.0"^^xsd:decimal = "10.0"^^xsd:double
        && "10.0"^^xsd:decimal = 1e1
        && "10.0"^^xsd:decimal = "1e1"^^xsd:float
        && "10.0"^^xsd:decimal = "1e1"^^xsd:double
        && "10.0"^^xsd:float = 10
        && "10.0"^^xsd:float = "10"^^xsd:integer
        && "10.0"^^xsd:float = "10"^^xsd:decimal
        && "10.0"^^xsd:float = "10"^^xsd:float
        && "10.0"^^xsd:float = "10"^^xsd:double
        && "10.0"^^xsd:float = 10.0
        && "10.0"^^xsd:float = "10"^^xsd:integer
        && "10.0"^^xsd:float = "10.0"^^xsd:decimal
        && "10.0"^^xsd:float = "10.0"^^xsd:float
        && "10.0"^^xsd:float = "10.0"^^xsd:double
        && "10.0"^^xsd:float = 1e1
        && "10.0"^^xsd:float = "1e1"^^xsd:float
        && "10.0"^^xsd:float = "1e1"^^xsd:double
        && "10.0"^^xsd:double = 10
        && "10.0"^^xsd:double = "10"^^xsd:integer
        && "10.0"^^xsd:double = "10"^^xsd:decimal
        && "10.0"^^xsd:double = "10"^^xsd:float
        && "10.0"^^xsd:double = "10"^^xsd:double
        && "10.0"^^xsd:double = 10.0
        && "10.0"^^xsd:double = "10"^^xsd:integer
        && "10.0"^^xsd:double = "10.0"^^xsd:decimal
        && "10.0"^^xsd:double = "10.0"^^xsd:float
        && "10.0"^^xsd:double = "10.0"^^xsd:double
        && "10.0"^^xsd:double = 1e1
        && "10.0"^^xsd:double = "1e1"^^xsd:float
        && "10.0"^^xsd:double = "1e1"^^xsd:double
        && 1e1 = 10
        && 1e1 = "10"^^xsd:integer
        && 1e1 = "10"^^xsd:decimal
        && 1e1 = "10"^^xsd:float
        && 1e1 = "10"^^xsd:double
        && 1e1 = 10.0
        && 1e1 = "10"^^xsd:integer
        && 1e1 = "10.0"^^xsd:decimal
        && 1e1 = "10.0"^^xsd:float
        && 1e1 = "10.0"^^xsd:double
        && 1e1 = 1e1
        && 1e1 = "1e1"^^xsd:float
        && 1e1 = "1e1"^^xsd:double
        && "1e1"^^xsd:float = 10
        && "1e1"^^xsd:float = "10"^^xsd:integer
        && "1e1"^^xsd:float = "10"^^xsd:decimal
        && "1e1"^^xsd:float = "10"^^xsd:float
        && "1e1"^^xsd:float = "10"^^xsd:double
        && "1e1"^^xsd:float = 10.0
        && "1e1"^^xsd:float = "10"^^xsd:integer
        && "1e1"^^xsd:float = "10.0"^^xsd:decimal
        && "1e1"^^xsd:float = "10.0"^^xsd:float
        && "1e1"^^xsd:float = "10.0"^^xsd:double
        && "1e1"^^xsd:float = 1e1
        && "1e1"^^xsd:float = "1e1"^^xsd:float
        && "1e1"^^xsd:float = "1e1"^^xsd:double
        && "1e1"^^xsd:double = 10
        && "1e1"^^xsd:double = "10"^^xsd:integer
        && "1e1"^^xsd:double = "10"^^xsd:decimal
        && "1e1"^^xsd:double = "10"^^xsd:float
        && "1e1"^^xsd:double = "10"^^xsd:double
        && "1e1"^^xsd:double = 10.0
        && "1e1"^^xsd:double = "10"^^xsd:integer
        && "1e1"^^xsd:double = "10.0"^^xsd:decimal
        && "1e1"^^xsd:double = "10.0"^^xsd:float
        && "1e1"^^xsd:double = "10.0"^^xsd:double
        && "1e1"^^xsd:double = 1e1
        && "1e1"^^xsd:double = "1e1"^^xsd:float
        && "1e1"^^xsd:double = "1e1"^^xsd:double
    )
}
