PREFIX : <http://www.firstPrefix.com/>
SELECT *
WHERE {
    :subjectFirstPrefix :predicateFirstPrefix ?o .
    FILTER (true
        && !(false || false)
        && (false || true)
        && (true || false)
        && (true || true)
    )
}
