
PREFIX : <https://example.com/>

SELECT *
WHERE {
:s :p
<aaa:millenniumdb>,
<aaas:millenniumdb>,
<about:millenniumdb>,
<acap:millenniumdb>,
<acct:millenniumdb>,
<acd:millenniumdb>,
<acr:millenniumdb>,
<adiumxtra:millenniumdb>,
<adt:millenniumdb>,
<afp:millenniumdb>,
<afs:millenniumdb>,
<aim:millenniumdb>,
<amss:millenniumdb>,
<android:millenniumdb>,
<appdata:millenniumdb>,
<apt:millenniumdb>,
<ar:millenniumdb>,
<ark:millenniumdb>,
<at:millenniumdb>,
<attachment:millenniumdb>,
<aw:millenniumdb>,
<barion:millenniumdb>,
<bb:millenniumdb>,
<beshare:millenniumdb>,
<bitcoin:millenniumdb>,
<bitcoincash:millenniumdb>,
<blob:millenniumdb>,
<bolo:millenniumdb>,
<brid:millenniumdb>,
<browserext:millenniumdb>,
<cabal:millenniumdb>,
<calculator:millenniumdb>,
<callto:millenniumdb>,
<cap:millenniumdb>,
<cast:millenniumdb>,
<casts:millenniumdb>,
<chrome:millenniumdb>,
<chrome-extension:millenniumdb>,
<cid:millenniumdb>,
<coap:millenniumdb>,
<coap+tcp:millenniumdb>,
<coap+ws:millenniumdb>,
<coaps:millenniumdb>,
<coaps+tcp:millenniumdb>,
<coaps+ws:millenniumdb>,
<com-eventbrite-attendee:millenniumdb>,
<content:millenniumdb>,
<content-type:millenniumdb>,
<crid:millenniumdb>,
<cstr:millenniumdb>,
<cvs:millenniumdb>,
<dab:millenniumdb>,
<dat:millenniumdb>,
<data:millenniumdb>,
<dav:millenniumdb>,
<dhttp:millenniumdb>,
<diaspora:millenniumdb>,
<dict:millenniumdb>,
<did:millenniumdb>,
<dis:millenniumdb>,
<dlna-playcontainer:millenniumdb>,
<dlna-playsingle:millenniumdb>,
<dns:millenniumdb>,
<dntp:millenniumdb>,
<doi:millenniumdb>,
<dpp:millenniumdb>,
<drm:millenniumdb>,
<drop:millenniumdb>,
<dtmi:millenniumdb>,
<dtn:millenniumdb>,
<dvb:millenniumdb>,
<dvx:millenniumdb>,
<dweb:millenniumdb>,
<ed2k:millenniumdb>,
<eid:millenniumdb>,
<elsi:millenniumdb>,
<embedded:millenniumdb>,
<ens:millenniumdb>,
<ethereum:millenniumdb>,
<example:millenniumdb>,
<facetime:millenniumdb>,
<fax:millenniumdb>,
<feed:millenniumdb>,
<feedready:millenniumdb>,
<fido:millenniumdb>,
<file:millenniumdb>,
<filesystem:millenniumdb>,
<finger:millenniumdb>,
<first-run-pen-experience:millenniumdb>,
<fish:millenniumdb>,
<fm:millenniumdb>,
<ftp:millenniumdb>,
<fuchsia-pkg:millenniumdb>,
<geo:millenniumdb>,
<gg:millenniumdb>,
<git:millenniumdb>,
<gitoid:millenniumdb>,
<gizmoproject:millenniumdb>,
<go:millenniumdb>,
<gopher:millenniumdb>,
<graph:millenniumdb>,
<grd:millenniumdb>,
<gtalk:millenniumdb>,
<h323:millenniumdb>,
<ham:millenniumdb>,
<hcap:millenniumdb>,
<hcp:millenniumdb>,
<http:millenniumdb>,
<https:millenniumdb>,
<hxxp:millenniumdb>,
<hxxps:millenniumdb>,
<hydrazone:millenniumdb>,
<hyper:millenniumdb>,
<iax:millenniumdb>,
<icap:millenniumdb>,
<icon:millenniumdb>,
<im:millenniumdb>,
<imap:millenniumdb>,
<info:millenniumdb>,
<iotdisco:millenniumdb>,
<ipfs:millenniumdb>,
<ipn:millenniumdb>,
<ipns:millenniumdb>,
<ipp:millenniumdb>,
<ipps:millenniumdb>,
<irc:millenniumdb>,
<irc6:millenniumdb>,
<ircs:millenniumdb>,
<iris:millenniumdb>,
<iris.beep:millenniumdb>,
<iris.lwz:millenniumdb>,
<iris.xpc:millenniumdb>,
<iris.xpcs:millenniumdb>,
<isostore:millenniumdb>,
<itms:millenniumdb>,
<jabber:millenniumdb>,
<jar:millenniumdb>,
<jms:millenniumdb>,
<keyparc:millenniumdb>,
<lastfm:millenniumdb>,
<lbry:millenniumdb>,
<ldap:millenniumdb>,
<ldaps:millenniumdb>,
<leaptofrogans:millenniumdb>,
<lid:millenniumdb>,
<lorawan:millenniumdb>,
<lpa:millenniumdb>,
<lvlt:millenniumdb>,
<machineProvisioningProgressReporter:millenniumdb>,
<magnet:millenniumdb>,
<mailserver:millenniumdb>,
<mailto:millenniumdb>,
<maps:millenniumdb>,
<market:millenniumdb>,
<matrix:millenniumdb>,
<message:millenniumdb>,
<microsoft.windows.camera:millenniumdb>,
<microsoft.windows.camera.multipicker:millenniumdb>,
<microsoft.windows.camera.picker:millenniumdb>,
<mid:millenniumdb>,
<mms:millenniumdb>,
<modem:millenniumdb>,
<mongodb:millenniumdb>,
<moz:millenniumdb>,
<ms-access:millenniumdb>,
<ms-appinstaller:millenniumdb>,
<ms-browser-extension:millenniumdb>,
<ms-calculator:millenniumdb>,
<ms-drive-to:millenniumdb>,
<ms-enrollment:millenniumdb>,
<ms-excel:millenniumdb>,
<ms-eyecontrolspeech:millenniumdb>,
<ms-gamebarservices:millenniumdb>,
<ms-gamingoverlay:millenniumdb>,
<ms-getoffice:millenniumdb>,
<ms-help:millenniumdb>,
<ms-infopath:millenniumdb>,
<ms-inputapp:millenniumdb>,
<ms-launchremotedesktop:millenniumdb>,
<ms-lockscreencomponent-config:millenniumdb>,
<ms-media-stream-id:millenniumdb>,
<ms-meetnow:millenniumdb>,
<ms-mixedrealitycapture:millenniumdb>,
<ms-mobileplans:millenniumdb>,
<ms-newsandinterests:millenniumdb>,
<ms-officeapp:millenniumdb>,
<ms-people:millenniumdb>,
<ms-project:millenniumdb>,
<ms-powerpoint:millenniumdb>,
<ms-publisher:millenniumdb>,
<ms-remotedesktop:millenniumdb>,
<ms-remotedesktop-launch:millenniumdb>,
<ms-restoretabcompanion:millenniumdb>,
<ms-screenclip:millenniumdb>,
<ms-screensketch:millenniumdb>,
<ms-search:millenniumdb>,
<ms-search-repair:millenniumdb>,
<ms-secondary-screen-controller:millenniumdb>,
<ms-secondary-screen-setup:millenniumdb>,
<ms-settings:millenniumdb>,
<ms-settings-airplanemode:millenniumdb>,
<ms-settings-bluetooth:millenniumdb>,
<ms-settings-camera:millenniumdb>,
<ms-settings-cellular:millenniumdb>,
<ms-settings-cloudstorage:millenniumdb>,
<ms-settings-connectabledevices:millenniumdb>,
<ms-settings-displays-topology:millenniumdb>,
<ms-settings-emailandaccounts:millenniumdb>,
<ms-settings-language:millenniumdb>,
<ms-settings-location:millenniumdb>,
<ms-settings-lock:millenniumdb>,
<ms-settings-nfctransactions:millenniumdb>,
<ms-settings-notifications:millenniumdb>,
<ms-settings-power:millenniumdb>,
<ms-settings-privacy:millenniumdb>,
<ms-settings-proximity:millenniumdb>,
<ms-settings-screenrotation:millenniumdb>,
<ms-settings-wifi:millenniumdb>,
<ms-settings-workplace:millenniumdb>,
<ms-spd:millenniumdb>,
<ms-stickers:millenniumdb>,
<ms-sttoverlay:millenniumdb>,
<ms-transit-to:millenniumdb>,
<ms-useractivityset:millenniumdb>,
<ms-virtualtouchpad:millenniumdb>,
<ms-visio:millenniumdb>,
<ms-walk-to:millenniumdb>,
<ms-whiteboard:millenniumdb>,
<ms-whiteboard-cmd:millenniumdb>,
<ms-word:millenniumdb>,
<msnim:millenniumdb>,
<msrp:millenniumdb>,
<msrps:millenniumdb>,
<mss:millenniumdb>,
<mt:millenniumdb>,
<mtqp:millenniumdb>,
<mumble:millenniumdb>,
<mupdate:millenniumdb>,
<mvn:millenniumdb>,
<mvrp:millenniumdb>,
<mvrps:millenniumdb>,
<news:millenniumdb>,
<nfs:millenniumdb>,
<ni:millenniumdb>,
<nih:millenniumdb>,
<nntp:millenniumdb>,
<notes:millenniumdb>,
<num:millenniumdb>,
<ocf:millenniumdb>,
<oid:millenniumdb>,
<onenote:millenniumdb>,
<onenote-cmd:millenniumdb>,
<opaquelocktoken:millenniumdb>,
<openid:millenniumdb>,
<openpgp4fpr:millenniumdb>,
<otpauth:millenniumdb>,
<p1:millenniumdb>,
<pack:millenniumdb>,
<palm:millenniumdb>,
<paparazzi:millenniumdb>,
<payment:millenniumdb>,
<payto:millenniumdb>,
<pkcs11:millenniumdb>,
<platform:millenniumdb>,
<pop:millenniumdb>,
<pres:millenniumdb>,
<prospero:millenniumdb>,
<proxy:millenniumdb>,
<pwid:millenniumdb>,
<psyc:millenniumdb>,
<pttp:millenniumdb>,
<qb:millenniumdb>,
<query:millenniumdb>,
<quic-transport:millenniumdb>,
<redis:millenniumdb>,
<rediss:millenniumdb>,
<reload:millenniumdb>,
<res:millenniumdb>,
<resource:millenniumdb>,
<rmi:millenniumdb>,
<rsync:millenniumdb>,
<rtmfp:millenniumdb>,
<rtmp:millenniumdb>,
<rtsp:millenniumdb>,
<rtsps:millenniumdb>,
<rtspu:millenniumdb>,
<sarif:millenniumdb>,
<secondlife:millenniumdb>,
<secret-token:millenniumdb>,
<service:millenniumdb>,
<session:millenniumdb>,
<sftp:millenniumdb>,
<sgn:millenniumdb>,
<shc:millenniumdb>,
<shttp:millenniumdb>,
<sieve:millenniumdb>,
<simpleledger:millenniumdb>,
<simplex:millenniumdb>,
<sip:millenniumdb>,
<sips:millenniumdb>,
<skype:millenniumdb>,
<smb:millenniumdb>,
<smp:millenniumdb>,
<sms:millenniumdb>,
<smtp:millenniumdb>,
<snews:millenniumdb>,
<snmp:millenniumdb>,
<soap.beep:millenniumdb>,
<soap.beeps:millenniumdb>,
<soldat:millenniumdb>,
<spiffe:millenniumdb>,
<spotify:millenniumdb>,
<ssb:millenniumdb>,
<ssh:millenniumdb>,
<starknet:millenniumdb>,
<steam:millenniumdb>,
<stun:millenniumdb>,
<stuns:millenniumdb>,
<submit:millenniumdb>,
<svn:millenniumdb>,
<swh:millenniumdb>,
<swid:millenniumdb>,
<swidpath:millenniumdb>,
<tag:millenniumdb>,
<taler:millenniumdb>,
<teamspeak:millenniumdb>,
<tel:millenniumdb>,
<teliaeid:millenniumdb>,
<telnet:millenniumdb>,
<tftp:millenniumdb>,
<things:millenniumdb>,
<thismessage:millenniumdb>,
<tip:millenniumdb>,
<tn3270:millenniumdb>,
<tool:millenniumdb>,
<turn:millenniumdb>,
<turns:millenniumdb>,
<tv:millenniumdb>,
<udp:millenniumdb>,
<unreal:millenniumdb>,
<upt:millenniumdb>,
<urn:millenniumdb>,
<ut2004:millenniumdb>,
<uuid-in-package:millenniumdb>,
<v-event:millenniumdb>,
<vemmi:millenniumdb>,
<ventrilo:millenniumdb>,
<ves:millenniumdb>,
<videotex:millenniumdb>,
<vnc:millenniumdb>,
<view-source:millenniumdb>,
<vscode:millenniumdb>,
<vscode-insiders:millenniumdb>,
<vsls:millenniumdb>,
<w3:millenniumdb>,
<wais:millenniumdb>,
<web3:millenniumdb>,
<wcr:millenniumdb>,
<webcal:millenniumdb>,
<web+ap:millenniumdb>,
<wifi:millenniumdb>,
<wpid:millenniumdb>,
<ws:millenniumdb>,
<wss:millenniumdb>,
<wtai:millenniumdb>,
<wyciwyg:millenniumdb>,
<xcon:millenniumdb>,
<xcon-userid:millenniumdb>,
<xfire:millenniumdb>,
<xmlrpc.beep:millenniumdb>,
<xmlrpc.beeps:millenniumdb>,
<xmpp:millenniumdb>,
<xftp:millenniumdb>,
<xrcp:millenniumdb>,
<xri:millenniumdb>,
<ymsgr:millenniumdb>,
<z39.50:millenniumdb>,
<z39.50r:millenniumdb>,
<z39.50s:millenniumdb> .
}