#include "object_id.h"

std::string to_string(ObjectType type)
{
    switch (type) {
    case ObjectType::Null:
        return "Null";
    case ObjectType::AnonInl:
        return "AnonInl";
    case ObjectType::AnonTmp:
        return "AnonTmp";
    case ObjectType::Bool:
        return "Bool";
    case ObjectType::NegativeInt56:
        return "NegativeInt56";
    case ObjectType::PositiveInt56:
        return "PositiveInt56";
    case ObjectType::Float:
        return "Float";
    case ObjectType::DoubleExt:
        return "DoubleExt";
    case ObjectType::DoubleTmp:
        return "DoubleTmp";
    case ObjectType::DecimalInl:
        return "DecimalInl";
    case ObjectType::DecimalExt:
        return "DecimalExt";
    case ObjectType::DecimalTmp:
        return "DecimalTmp";
    case ObjectType::StringInl:
        return "StringInl";
    case ObjectType::StringExt:
        return "StringExt";
    case ObjectType::StringTmp:
        return "StringTmp";
    case ObjectType::StringXsdInl:
        return "StringXsdInl";
    case ObjectType::StringXsdExt:
        return "StringXsdExt";
    case ObjectType::StringXsdTmp:
        return "StringXsdTmp";
    case ObjectType::StringLangInl:
        return "StringLangInl";
    case ObjectType::StringLangExt:
        return "StringLangExt";
    case ObjectType::StringLangTmp:
        return "StringLangTmp";
    case ObjectType::StringDatatypeInl:
        return "StringDatatypeInl";
    case ObjectType::StringDatatypeExt:
        return "StringDatatypeExt";
    case ObjectType::StringDatatypeTmp:
        return "StringDatatypeTmp";
    case ObjectType::IriInl:
        return "IriInl";
    case ObjectType::IriExt:
        return "IriExt";
    case ObjectType::IriTmp:
        return "IriTmp";
    case ObjectType::IriUuidLowerTmp:
        return "IriUuidLowerTmp";
    case ObjectType::IriUuidLowerExt:
        return "IriUuidLowerExt";
    case ObjectType::IriUuidUpperTmp:
        return "IriUuidUpperTmp";
    case ObjectType::IriUuidUpperExt:
        return "IriUuidUpperExt";
    case ObjectType::IriHexLowerTmp:
        return "IriHexLowerTmp";
    case ObjectType::IriHexLowerExt:
        return "IriHexLowerExt";
    case ObjectType::IriHexUpperTmp:
        return "IriHexUpperTmp";
    case ObjectType::IriHexUpperExt:
        return "IriHexUpperExt";
    case ObjectType::NamedNodeInl:
        return "NamedNodeInl";
    case ObjectType::NamedNodeExt:
        return "NamedNodeExt";
    case ObjectType::NamedNodeTmp:
        return "NamedNodeTmp";
    case ObjectType::Time:
        return "Time";
    case ObjectType::Date:
        return "Date";
    case ObjectType::Datetime:
        return "Datetime";
    case ObjectType::Datetimestamp:
        return "Datetimestamp";
    case ObjectType::TensorFloatExt:
        return "TensorFloatExt";
    case ObjectType::TensorFloatTmp:
        return "TensorFloatTmp";
    case ObjectType::TensorDoubleExt:
        return "TensorDoubleExt";
    case ObjectType::TensorDoubleTmp:
        return "TensorDoubleTmp";
    case ObjectType::DictionaryExt:
        return "DictionaryExt";
    case ObjectType::DictionaryTmp:
        return "DictionaryTmp";
    case ObjectType::ListExt:
        return "ListExt";
    case ObjectType::ListTmp:
        return "ListTmp";
    case ObjectType::DirectedEdge:
        return "DirectedEdge";
    case ObjectType::UndirectedEdge:
        return "UndirectedEdge";
    case ObjectType::EdgeKey:
        return "EdgeKey";
    case ObjectType::NodeKey:
        return "NodeKey";
    case ObjectType::EdgeLabel:
        return "EdgeLabel";
    case ObjectType::NodeLabel:
        return "NodeLabel";
    case ObjectType::Path:
        return "Path";
    case ObjectType::NotFound:
        return "NotFound";
        break;
    }
    return "Unknown";
}

std::string to_string(ObjectSubType type)
{
    switch (type) {
    case ObjectSubType::Null:
        return "Null";
    case ObjectSubType::Bool:
        return "Bool";
    case ObjectSubType::Int:
        return "Int";
    case ObjectSubType::Float:
        return "Float";
    case ObjectSubType::Double:
        return "Double";
    case ObjectSubType::Decimal:
        return "Decimal";
    case ObjectSubType::TemporalLiteral:
        return "TemporalLiteral";
    case ObjectSubType::String:
        return "String";
    case ObjectSubType::StringXsd:
        return "StringXsd";
    case ObjectSubType::StringLang:
        return "StringLang";
    case ObjectSubType::StringDatatype:
        return "StringDatatype";
    case ObjectSubType::TensorFloat:
        return "TensorFloat";
    case ObjectSubType::TensorDouble:
        return "TensorDouble";
    case ObjectSubType::Dictionary:
        return "Dictionary";
    case ObjectSubType::List:
        return "List";
    case ObjectSubType::Anon:
        return "Anon";
    case ObjectSubType::NamedNode:
        return "NamedNode";
    case ObjectSubType::Edge:
        return "Edge";
    case ObjectSubType::Path:
        return "Path";
    case ObjectSubType::Iri:
        return "Iri";
    case ObjectSubType::NotFound:
        return "NotFound";
    }
    return "Unknown";
}

std::string to_string(ObjectGenType type)
{
    switch (type) {
    case ObjectGenType::Null:
        return "Null";
    case ObjectGenType::Bool:
        return "Bool";
    case ObjectGenType::TemporalLiteral:
        return "TemporalLiteral";
    case ObjectGenType::String:
        return "String";
    case ObjectGenType::Numeric:
        return "Numeric";
    case ObjectGenType::Tensor:
        return "Tensor";
    case ObjectGenType::List:
        return "List";
    case ObjectGenType::Dict:
        return "Dict";
    case ObjectGenType::Anon:
        return "Anon";
    case ObjectGenType::NamedNode:
        return "NamedNode";
    case ObjectGenType::Edge:
        return "Edge";
    case ObjectGenType::Path:
        return "Path";
    case ObjectGenType::Iri:
        return "Iri";
    case ObjectGenType::NotFound:
        return "NotFound";
    }
    return "Unknown";
}