/* Generated by re2c 4.3 on Wed Jan 21 15:13:47 2026 */
#line 1 "tokenizer_template.cpp"
// re2c tokenizer_template.cpp -o tokenizer.cc
#include <cstring>

#include "import/gql/lexer/token.h"
#include "import/gql/lexer/tokenizer.h"
#include "system/string_manager.h"

#line 11 "tokenizer.cc"
#define YYMAXFILL 6
#line 8 "tokenizer_template.cpp"

static const size_t GQLTokenizer_SIZE = StringManager::MAX_STRING_SIZE;

GQLTokenizer::GQLTokenizer() :
    _str(new char[GQLTokenizer_SIZE + YYMAXFILL]),
    buf(new char[GQLTokenizer_SIZE + YYMAXFILL]),
    lim(buf + GQLTokenizer_SIZE),
    cur(lim),
    mar(lim),
    token_start(lim),
    eof(false)
{ }

GQLTokenizer::~GQLTokenizer()
{
    delete[] buf;
    delete[] str;
}

void GQLTokenizer::begin(MDBIstream& in)
{
    this->in = &in;
}

bool GQLTokenizer::fill(size_t need)
{
    if (eof) {
        return false;
    }
    const size_t free = token_start - buf;
    if (free < need) {
        return false;
    }
    memmove(buf, token_start, lim - token_start);
    lim -= free;
    cur -= free;
    mar -= free;
    token_start -= free;
    // std::cout << "trying to read " << free << " bytes\n";
    auto r = in->read(lim, free);
    // std::cout << "read " << r << " bytes\n";
    lim += r;

    if (lim < buf + GQLTokenizer_SIZE) {
        if (r == 0)
            return false;
        eof = true;
        memset(lim, 0, YYMAXFILL);
        lim += YYMAXFILL - 1;
    }
    return true;
}

Import::GQL::Token GQLTokenizer::get_token()
{
    auto res = _get_token();

    str_len = cur - token_start;

    std::memcpy(_str, token_start, str_len);
    _str[str_len] = '\0';

    str = _str;

    return res;
}

Import::GQL::Token GQLTokenizer::_get_token()
{
    token_start = cur;
    
#line 85 "tokenizer.cc"
{
	char yych;
	unsigned int yyaccept = 0;
	if ((lim - cur) < 6) if (!fill(6)) return Import::GQL::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy3;
		case '\n': goto yy5;
		case '"': goto yy6;
		case '+': goto yy7;
		case ',': goto yy8;
		case '-': goto yy9;
		case '.': goto yy10;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy11;
		case ':': goto yy13;
		case '<': goto yy14;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		case '[': goto yy17;
		case ']': goto yy18;
		case 'f': goto yy19;
		case 't': goto yy20;
		case '~': goto yy21;
		default: goto yy1;
	}
yy1:
	++cur;
yy2:
#line 120 "tokenizer_template.cpp"
	{ return Import::GQL::Token::UNRECOGNIZED; }
#line 175 "tokenizer.cc"
yy3:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::GQL::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy3;
		default: goto yy4;
	}
yy4:
#line 115 "tokenizer_template.cpp"
	{ return Import::GQL::Token::WHITESPACE; }
#line 189 "tokenizer.cc"
yy5:
	++cur;
#line 116 "tokenizer_template.cpp"
	{ return Import::GQL::Token::ENDLINE; }
#line 194 "tokenizer.cc"
yy6:
	yyaccept = 0;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\n': goto yy2;
		default: goto yy23;
	}
yy7:
	yyaccept = 0;
	yych = *(mar = ++cur);
	switch (yych) {
		case '.': goto yy27;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy11;
		default: goto yy2;
	}
yy8:
	++cur;
#line 119 "tokenizer_template.cpp"
	{ return Import::GQL::Token::COMMA; }
#line 223 "tokenizer.cc"
yy9:
	yyaccept = 0;
	yych = *(mar = ++cur);
	switch (yych) {
		case '.': goto yy27;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy11;
		case '>': goto yy28;
		default: goto yy2;
	}
yy10:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy29;
		default: goto yy2;
	}
yy11:
	yyaccept = 1;
	mar = ++cur;
	if ((lim - cur) < 3) if (!fill(3)) return Import::GQL::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '.': goto yy27;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy11;
		case 'E':
		case 'e': goto yy31;
		default: goto yy12;
	}
yy12:
#line 113 "tokenizer_template.cpp"
	{ return Import::GQL::Token::INTEGER; }
#line 281 "tokenizer.cc"
yy13:
	++cur;
#line 104 "tokenizer_template.cpp"
	{ return Import::GQL::Token::COLON; }
#line 286 "tokenizer.cc"
yy14:
	yych = *++cur;
	switch (yych) {
		case '-': goto yy32;
		default: goto yy2;
	}
yy15:
	yyaccept = 2;
	mar = ++cur;
	if (lim <= cur) if (!fill(1)) return Import::GQL::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy33;
		case '(': goto yy34;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case '_': goto yy35;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		default: goto yy16;
	}
yy16:
#line 112 "tokenizer_template.cpp"
	{ return Import::GQL::Token::IDENTIFIER; }
#line 371 "tokenizer.cc"
yy17:
	++cur;
#line 117 "tokenizer_template.cpp"
	{ return Import::GQL::Token::L_BRACKET; }
#line 376 "tokenizer.cc"
yy18:
	++cur;
#line 118 "tokenizer_template.cpp"
	{ return Import::GQL::Token::R_BRACKET; }
#line 381 "tokenizer.cc"
yy19:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy33;
		case '(': goto yy34;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		case 'a': goto yy37;
		default: goto yy36;
	}
yy20:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy33;
		case '(': goto yy34;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		case 'r': goto yy38;
		default: goto yy36;
	}
yy21:
	++cur;
#line 107 "tokenizer_template.cpp"
	{ return Import::GQL::Token::UNDIRECTED; }
#line 510 "tokenizer.cc"
yy22:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::GQL::Token::END_OF_FILE;
	yych = *cur;
yy23:
	switch (yych) {
		case '\n': goto yy24;
		case '"': goto yy25;
		case '\\': goto yy26;
		default: goto yy22;
	}
yy24:
	cur = mar;
	switch (yyaccept) {
		case 0: goto yy2;
		case 1: goto yy12;
		case 2: goto yy16;
		case 3: goto yy30;
		case 4: goto yy48;
		default: goto yy51;
	}
yy25:
	++cur;
#line 110 "tokenizer_template.cpp"
	{ return Import::GQL::Token::STRING; }
#line 536 "tokenizer.cc"
yy26:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::GQL::Token::END_OF_FILE;
	goto yy22;
yy27:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy29;
		default: goto yy24;
	}
yy28:
	++cur;
#line 106 "tokenizer_template.cpp"
	{ return Import::GQL::Token::R_ARROW; }
#line 560 "tokenizer.cc"
yy29:
	yyaccept = 3;
	mar = ++cur;
	if ((lim - cur) < 3) if (!fill(3)) return Import::GQL::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy29;
		case 'E':
		case 'e': goto yy31;
		default: goto yy30;
	}
yy30:
#line 114 "tokenizer_template.cpp"
	{ return Import::GQL::Token::FLOAT; }
#line 584 "tokenizer.cc"
yy31:
	yych = *++cur;
	switch (yych) {
		case '+':
		case '-': goto yy39;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy40;
		default: goto yy24;
	}
yy32:
	++cur;
#line 105 "tokenizer_template.cpp"
	{ return Import::GQL::Token::L_ARROW; }
#line 606 "tokenizer.cc"
yy33:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::GQL::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy33;
		case '(': goto yy34;
		default: goto yy24;
	}
yy34:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::GQL::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy34;
		case '"': goto yy41;
		default: goto yy24;
	}
yy35:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::GQL::Token::END_OF_FILE;
	yych = *cur;
yy36:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy35;
		default: goto yy16;
	}
yy37:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy33;
		case '(': goto yy34;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		case 'l': goto yy42;
		default: goto yy36;
	}
yy38:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy33;
		case '(': goto yy34;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		case 'u': goto yy43;
		default: goto yy36;
	}
yy39:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy40;
		default: goto yy24;
	}
yy40:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::GQL::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy40;
		default: goto yy30;
	}
yy41:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::GQL::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\n': goto yy24;
		case '"': goto yy44;
		case '\\': goto yy45;
		default: goto yy41;
	}
yy42:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy33;
		case '(': goto yy34;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		case 's': goto yy46;
		default: goto yy36;
	}
yy43:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy33;
		case '(': goto yy34;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		case 'e': goto yy47;
		default: goto yy36;
	}
yy44:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::GQL::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy44;
		case ')': goto yy49;
		default: goto yy24;
	}
yy45:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::GQL::Token::END_OF_FILE;
	goto yy41;
yy46:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy33;
		case '(': goto yy34;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		case 'e': goto yy50;
		default: goto yy36;
	}
yy47:
	yyaccept = 4;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy33;
		case '(': goto yy34;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case '_': goto yy35;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		default: goto yy48;
	}
yy48:
#line 108 "tokenizer_template.cpp"
	{ return Import::GQL::Token::K_TRUE; }
#line 1143 "tokenizer.cc"
yy49:
	++cur;
#line 111 "tokenizer_template.cpp"
	{ return Import::GQL::Token::TYPED_STRING; }
#line 1148 "tokenizer.cc"
yy50:
	yyaccept = 5;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy33;
		case '(': goto yy34;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case '_': goto yy35;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		default: goto yy51;
	}
yy51:
#line 109 "tokenizer_template.cpp"
	{ return Import::GQL::Token::K_FALSE; }
#line 1225 "tokenizer.cc"
}
#line 121 "tokenizer_template.cpp"

    return Import::GQL::Token::END_OF_FILE;
}
