N0  :TestNode number:1 number2:2
N1  :TestNode number:2 number2:1
N2  :TestNode number:2 number2:1
N3  :TestNode number:3 number2:0
N4  :TestNode number:3 number2:2
N5  :TestNode number:3 number2:2
N6  :TestNode number:4 number2:2
N7  :TestNode number:4 number2:2
N8  :TestNode number:4 number2:2
N9  :TestNode number:4 number2:2
N10 :TestNode number:5 number2:2
N11 :TestNode number:5 number2:2
N12 :TestNode number:5 number2:2
N13 :TestNode number:5 number2:2
N14 :TestNode number:5 number2:2
N15 :TestNode number:6 number2:2
N16 :TestNode number:6 number2:2
N17 :TestNode number:6 number2:2
N18 :TestNode number:6 number2:2
N19 :TestNode number:6 number2:2
N20 :TestNode number:6 number2:2