ARG IMAGE=ubuntu
ARG VERSION=24.04
FROM ${IMAGE}:${VERSION}

# Define variables for this stage
ARG IMAGE
ARG VERSION
ENV PACKAGE=millenniumdb_0.2-1_${IMAGE}-${VERSION}_amd64

RUN apt-get update && apt-get -y install python3 python3-venv

WORKDIR /MillenniumDB

RUN python3 -m venv venv
RUN venv/bin/python3 -m pip install colorama rdflib sparqlwrapper tqdm

COPY deb-package/output/$PACKAGE.deb $PACKAGE.deb
RUN apt-get -y install ./$PACKAGE.deb

COPY deb-package/run-tests run-tests
COPY tests tests

CMD ./run-tests
