#pragma once

#include "query/parser/grammar/mql/autogenerated/MQL_ParserBaseVisitor.h"

namespace MQL {

class QueryIsUpdateVisitor : public MQL_ParserBaseVisitor {
public:
    bool is_update = false;

    virtual std::any visitUpdateStatement(MQL_Parser::UpdateStatementContext*) override
    {
        is_update = true;
        return 0;
    }

    virtual std::any visitCreateIndexQuery(MQL_Parser::CreateIndexQueryContext*) override
    {
        is_update = true;
        return 0;
    }
};
} // namespace MQL
