SELECT ?pname
WHERE {
    <http://www.absolute1.com/absoluteSubject> ANY_SHORTEST(<http://www.absolute1.com/absolutePredicate>+ AS ?pname) <http://www.absolute1.com/absoluteObject> .
    ?s ?pname ?o .
}
