PREFIX : <http://p.c/>
SELECT *
WHERE {
    ?s1 ?p1 ?o1 .
    ?s2 ?p2 ?o2 .
    ?s3 ?p3 ?o3 .

    FILTER(    EXISTS { ?s1 ?p1 ?o1 FILTER(STR(?s1) = STR(?o1)) } = ?o1)
    FILTER(NOT EXISTS { ?s1 ?p2 ?o2 FILTER(STR(?s1) = STR(?o2)) } = ?o1)
    FILTER(    EXISTS { ?s1 ?p3 ?o3 FILTER(STR(?s1) = STR(?o3)) } = ?o1)
    FILTER(NOT EXISTS { ?s1 ?p4 ?o4 FILTER(STR(?s1) = STR(?o4)) } = ?o1)
    FILTER(NOT EXISTS { ?s1 ?p5 ?o5 FILTER(STR(?s1) = STR(?o5)) } = ?o1)
    FILTER(NOT EXISTS { ?s1 ?p6 ?o6 FILTER(STR(?s1) = STR(?o6)) } = ?o1)
    FILTER(    EXISTS { ?s1 ?p7 ?o7 FILTER(STR(?s1) = STR(?o7)) } = ?o1)
    FILTER(    EXISTS { ?s1 ?p8 ?o8 FILTER(STR(?s1) = STR(?o8)) } = ?o1)
    FILTER(    EXISTS { ?s1 ?p9 ?o9 FILTER(STR(?s1) = STR(?o9)) } = ?o1)
}


# JsonSelectExecutor(?s1, ?p1, ?o1, ?s2, ?p2, ?o2, ?s3, ?p3, ?o3)
#   Filter(filtered: 0, passed: 0, (?s1=http://p.c/s), (?p1=http://p.c/p), (?o1=http://p.c/o), (?s2=http://p.c/s), (?p2=http://p.c/p), (?o2=http://p.c/o), (?s2=http://p.c/s), (?p2=http://p.c/p), (?o2=http://p.c/o))
#     LeapfrogJoin(found: 0, seeks: 0)


# JsonSelectExecutor(?s1, ?p1, ?o1, ?s2, ?p2, ?o2, ?s3, ?p3, ?o3)
#   Filter(filtered: 0, passed: 0,
#         ?s1=http://p.c/s
#         ?p1=http://p.c/p
#         ?o1=http://p.c/o
#         ?s2=http://p.c/s
#         ?p2=http://p.c/p
#         ?o2=http://p.c/o
#         ?s2=http://p.c/s
#         ?p2=http://p.c/p
#         ?o2=http://p.c/o
#     )
#     LeapfrogJoin(found: 0, seeks: 0)