#!/usr/bin/bash
set -e

# To enable debugging uncomment this line:
# set -x

# Configure build
cmake -Bbuild/Debug -DCMAKE_BUILD_TYPE=Debug

# Build
cmake --build build/Debug/ -j $(($(getconf _NPROCESSORS_ONLN)-1))

BLUE='\033[0;34m'
NC='\033[0m'

# Run unit tests
cd build/Debug/
printf "${BLUE}CTEST UNIT TESTS${NC}\n"
ctest --output-on-failure

# Run catch2 unit tests.
printf "${BLUE}CATCH2 UNIT TESTS\n"
./bin/catch2_tests
