#!/usr/bin/bash
set -e

# To enable debugging uncomment this line:
#set -x

BLUE='\033[0;34m'
NC='\033[0m'

# Configure build
cmake -Bbuild/Debug -DCMAKE_BUILD_TYPE=Debug

# Build
cmake --build build/Debug/ -j $(($(getconf _NPROCESSORS_ONLN)-1))

# Remove SPARQL tmp dir
[[ -d tests/sparql/tmp/ ]] && echo -e ${BLUE}Remove tests/sparql/tmp/${NC} && rm -r tests/sparql/tmp/

# Remove MQL tmp dir
[[ -d tests/mql/tmp/ ]] && echo -e ${BLUE}Remove tests/mql/tmp/${NC} && rm -r tests/mql/tmp/


# Run SPARQL integration tests
printf "${BLUE}SPARQL INTEGRATION TESTS${NC}\n"
python3 tests/sparql/scripts/test.py | tee >(sed $'s/\033[[][^A-Za-z]*m//g' > tests/sparql/test-status-last.txt)

# Run MQL integration tests
printf "${BLUE}MQL INTEGRATION TESTS${NC}\n"
python3 tests/mql/scripts/test.py | tee >(sed $'s/\033[[][^A-Za-z]*m//g' > tests/mql/test-status-last.txt)

# Run unit tests
cd build/Debug/
printf "${BLUE}CTEST UNIT TESTS${NC}\n"
ctest --output-on-failure

# Run catch2 unit tests.
# printf "${BLUE}CATCH2 UNIT TESTS\n"
# ./bin/catch2_tests
