#!/bin/bash

# Usage: sparql_update <query_file>
set -e; set -u; set -o pipefail

[[ ! ${1-} ]] && echo "Missing query file" && exit 1

curl -H "Content-Type:application/sparql-update" --data-binary "@$1" -X POST http://localhost:1234/update
echo ""
