N0 :import :strings prop:["N1", "000000001"]
N1 :import :numeric prop:[1, 3, 4]
N2 :import :bool    prop:[false, true, true, false, false, true]
N3 :import :nested  prop:[0, 1, 2, [10, 11, [20, 21], 12], 3, [10]]
N4 :import :empty   prop:[]
L5 :expr_in     prop:[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
L6 :expr_in     prop:[0, 0, 1, 1, 4, 1, 1, 0]
L7 :expr_in     prop:[10, 20, 30, 40, 50]
L8 :expr_in     prop:[-10, 1, 3, 4]
N0->N1 :t prop:["N0", "N1"]
N0->N2 :t prop:["N0", "N2"]
N0->N3 :t prop:["N0", "N3"]
