#pragma once

#include "misc/logger.h"
#include "query/parser/grammar/error_listener.h"
#include "query/parser/grammar/mql/autogenerated/MQL_Lexer.h"
#include "query/parser/grammar/mql/autogenerated/MQL_Parser.h"
#include "query/parser/grammar/mql/query_is_update_visitor.h"
#include "query/parser/grammar/mql/query_visitor.h"
#include "query/parser/op/mql/op.h"
#include "query/rewriter/mql/op/check_var_names.h"

namespace MQL {

class QueryParser {
public:
    antlr4::ANTLRInputStream input;
    MQL_Lexer lexer;
    antlr4::CommonTokenStream tokens;
    MQL_Parser parser;
    antlr4::MyErrorListener error_listener;

    MQL_Parser::RootContext* root;

    QueryParser(const std::string& query) :
        input(query),
        lexer(&input),
        tokens(&lexer),
        parser(&tokens)
    {
        parser.getInterpreter<antlr4::atn::ParserATNSimulator>()->setPredictionMode(
            antlr4::atn::PredictionMode::SLL
        );

        parser.removeErrorListeners();
        parser.addErrorListener(&error_listener);
        root = parser.root();
    }

    bool is_update()
    {
        QueryIsUpdateVisitor visitor;
        visitor.visitRoot(root);

        return visitor.is_update;
    }

    std::unique_ptr<Op> get_query_plan()
    {
        QueryVisitor visitor;
        visitor.visitRoot(root);

        auto res = std::move(visitor.current_op);

        // logger(Category::LogicalPlan) << "Initial logical plan:\n" << *res;

        CheckVarNames check_var_names;
        res->accept_visitor(check_var_names);

        // TODO:
        // CheckWellDesigned check_well_designed;
        // res->accept_visitor(check_well_designed);

        // TODO:
        // OptimizeOptionalTree optimize_optional_tree;
        // res->accept_visitor(optimize_optional_tree);

        // TODO: push negation inside, simplify constant expressions
        // PushWhere push_where;
        // res->accept_visitor(push_where);

        logger(Category::LogicalPlan) << *res;

        return res;
    }
};
} // namespace MQL
