N0 :Person name:"N0"
N1 :Person name:"N1"
N2 :Person name:"N2"
N3 :Person name:"N3"
N4 :Person name:"N4"
N5 :Person name:"N5"
B6 :Book name:"B6"
B7 :Book name:"B7"
B8 :Book name:"B8"
B9 :Book name:"B9"
N0->N1 :Follows name:"F0"
N0->N2 :Follows name:"F1"
N1->N3 :Follows name:"F2"
N1->N4 :Follows name:"F3"
N2->N0 :Follows name:"F4"
N2->N3 :Follows name:"F5"
N2->N5 :Follows name:"F6"
N3->N4 :Follows name:"F7"
N4->N1 :Follows name:"F8"
N0->B9 :Owns name:"O9"
N1->B9 :Owns name:"O10"
N2->B6 :Owns name:"O11"
N2->B7 :Owns name:"O12"
N2->B8 :Owns name:"O13"
N3->B7 :Owns name:"O14"
N4->B6 :Owns name:"O15"
N4->B8 :Owns name:"O16"
U10 :Article
U11 :Article
U12 :Article
U13 :Article
U10~U11 name:"U0"
U10~U12 name:"U1"
U11~U13 name:"U2"
U12~U13 name:"U3"
U13~N0 name:"U4"
