# src=https://www.w3.org/2008/07/MappingRules/StemMapping
PREFIX emplP: <http://hr.example/DB/Employee#>

SELECT ?empName ?managName
WHERE {
    ?emp      emplP:lastName   ?empName .
    ?emp      emplP:manager    ?manager .
    ?manager  emplP:lastName   ?managName .
}