/* Generated by re2c 3.0 on Mon Oct  6 12:03:34 2025 */
#line 1 "tokenizer_template.cpp"
// re2c tokenizer_template.cpp -o tokenizer.cc
#include <cstring>

#include "import/quad_model/lexer/token.h"
#include "import/quad_model/lexer/tokenizer.h"
#include "system/string_manager.h"

#line 11 "tokenizer.cc"
#define YYMAXFILL 6
#line 8 "tokenizer_template.cpp"

constexpr size_t MQLTokenizer_SIZE = StringManager::MAX_STRING_SIZE;

MQLTokenizer::MQLTokenizer() :
    _str(new char[MQLTokenizer_SIZE + YYMAXFILL]),
    buf(new char[MQLTokenizer_SIZE + YYMAXFILL]),
    lim(buf + MQLTokenizer_SIZE),
    cur(lim),
    mar(lim),
    token_start(lim),
    eof(false)
{ }

MQLTokenizer::~MQLTokenizer()
{
    delete[] buf;
    delete[] str;
}

void MQLTokenizer::begin(MDBIstream& in)
{
    this->in = &in;
}

bool MQLTokenizer::fill(size_t need)
{
    if (eof) {
        return false;
    }
    const size_t free = token_start - buf;
    if (free < need) {
        return false;
    }
    memmove(buf, token_start, lim - token_start);
    lim -= free;
    cur -= free;
    mar -= free;
    token_start -= free;
    // std::cout << "trying to read " << free << " bytes\n";
    auto r = in->read(lim, free);
    // std::cout << "read " << r << " bytes\n";
    lim += r;

    if (lim < buf + MQLTokenizer_SIZE) {
        if (r == 0)
            return false;
        eof = true;
        memset(lim, 0, YYMAXFILL);
        lim += YYMAXFILL - 1;
    }
    return true;
}

Import::QuadModel::Token MQLTokenizer::get_token()
{
    auto res = _get_token();

    str_len = cur - token_start;

    std::memcpy(_str, token_start, str_len);
    _str[str_len] = '\0';

    str = _str;

    return res;
}

Import::QuadModel::Token MQLTokenizer::_get_token()
{
    token_start = cur;
    
#line 85 "tokenizer.cc"
{
	char yych;
	unsigned int yyaccept = 0;
	if ((lim - cur) < 6) if (!fill(6)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy3;
		case '\n': goto yy5;
		case '"': goto yy6;
		case '+': goto yy7;
		case ',': goto yy8;
		case '-': goto yy9;
		case '.': goto yy10;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy11;
		case ':': goto yy13;
		case '<': goto yy14;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		case '[': goto yy17;
		case ']': goto yy18;
		case 'f': goto yy19;
		case 't': goto yy20;
		default: goto yy1;
	}
yy1:
	++cur;
yy2:
#line 118 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::UNRECOGNIZED; }
#line 174 "tokenizer.cc"
yy3:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy3;
		default: goto yy4;
	}
yy4:
#line 113 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::WHITESPACE; }
#line 188 "tokenizer.cc"
yy5:
	++cur;
#line 117 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::ENDLINE; }
#line 193 "tokenizer.cc"
yy6:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '"': goto yy21;
		case '\\': goto yy22;
		default: goto yy6;
	}
yy7:
	yyaccept = 0;
	yych = *(mar = ++cur);
	switch (yych) {
		case '.': goto yy23;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy11;
		default: goto yy2;
	}
yy8:
	++cur;
#line 116 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::COMMA; }
#line 224 "tokenizer.cc"
yy9:
	yyaccept = 0;
	yych = *(mar = ++cur);
	switch (yych) {
		case '.': goto yy23;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy11;
		case '>': goto yy25;
		default: goto yy2;
	}
yy10:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy26;
		default: goto yy2;
	}
yy11:
	yyaccept = 1;
	mar = ++cur;
	if ((lim - cur) < 3) if (!fill(3)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '.': goto yy23;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy11;
		case 'E':
		case 'e': goto yy28;
		default: goto yy12;
	}
yy12:
#line 111 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::INTEGER; }
#line 282 "tokenizer.cc"
yy13:
	++cur;
#line 103 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::COLON; }
#line 287 "tokenizer.cc"
yy14:
	yych = *++cur;
	switch (yych) {
		case '-': goto yy29;
		default: goto yy2;
	}
yy15:
	yyaccept = 2;
	mar = ++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy30;
		case '(': goto yy31;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case '_': goto yy32;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		default: goto yy16;
	}
yy16:
#line 110 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::IDENTIFIER; }
#line 372 "tokenizer.cc"
yy17:
	++cur;
#line 114 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::L_BRACKET; }
#line 377 "tokenizer.cc"
yy18:
	++cur;
#line 115 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::R_BRACKET; }
#line 382 "tokenizer.cc"
yy19:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy30;
		case '(': goto yy31;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		case 'a': goto yy34;
		default: goto yy33;
	}
yy20:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy30;
		case '(': goto yy31;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		case 'r': goto yy35;
		default: goto yy33;
	}
yy21:
	++cur;
#line 108 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::STRING; }
#line 511 "tokenizer.cc"
yy22:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	goto yy6;
yy23:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy26;
		default: goto yy24;
	}
yy24:
	cur = mar;
	switch (yyaccept) {
		case 0: goto yy2;
		case 1: goto yy12;
		case 2: goto yy16;
		case 3: goto yy27;
		case 4: goto yy45;
		default: goto yy48;
	}
yy25:
	++cur;
#line 105 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::R_ARROW; }
#line 545 "tokenizer.cc"
yy26:
	yyaccept = 3;
	mar = ++cur;
	if ((lim - cur) < 3) if (!fill(3)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy26;
		case 'E':
		case 'e': goto yy28;
		default: goto yy27;
	}
yy27:
#line 112 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::FLOAT; }
#line 569 "tokenizer.cc"
yy28:
	yych = *++cur;
	switch (yych) {
		case '+':
		case '-': goto yy36;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy37;
		default: goto yy24;
	}
yy29:
	++cur;
#line 104 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::L_ARROW; }
#line 591 "tokenizer.cc"
yy30:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy30;
		case '(': goto yy31;
		default: goto yy24;
	}
yy31:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy31;
		case '"': goto yy38;
		default: goto yy24;
	}
yy32:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
yy33:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy32;
		default: goto yy16;
	}
yy34:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy30;
		case '(': goto yy31;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		case 'l': goto yy39;
		default: goto yy33;
	}
yy35:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy30;
		case '(': goto yy31;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		case 'u': goto yy40;
		default: goto yy33;
	}
yy36:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy37;
		default: goto yy24;
	}
yy37:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy37;
		default: goto yy27;
	}
yy38:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '"': goto yy41;
		case '\\': goto yy42;
		default: goto yy38;
	}
yy39:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy30;
		case '(': goto yy31;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		case 's': goto yy43;
		default: goto yy33;
	}
yy40:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy30;
		case '(': goto yy31;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		case 'e': goto yy44;
		default: goto yy33;
	}
yy41:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	yych = *cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy41;
		case ')': goto yy46;
		default: goto yy24;
	}
yy42:
	++cur;
	if (lim <= cur) if (!fill(1)) return Import::QuadModel::Token::END_OF_FILE;
	goto yy38;
yy43:
	yyaccept = 2;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy30;
		case '(': goto yy31;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		case 'e': goto yy47;
		default: goto yy33;
	}
yy44:
	yyaccept = 4;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy30;
		case '(': goto yy31;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case '_': goto yy32;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		default: goto yy45;
	}
yy45:
#line 106 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::K_TRUE; }
#line 1127 "tokenizer.cc"
yy46:
	++cur;
#line 109 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::TYPED_STRING; }
#line 1132 "tokenizer.cc"
yy47:
	yyaccept = 5;
	yych = *(mar = ++cur);
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy30;
		case '(': goto yy31;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case '_': goto yy32;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy15;
		default: goto yy48;
	}
yy48:
#line 107 "tokenizer_template.cpp"
	{ return Import::QuadModel::Token::K_FALSE; }
#line 1209 "tokenizer.cc"
}
#line 119 "tokenizer_template.cpp"

    return Import::QuadModel::Token::END_OF_FILE;
}
