#!/bin/zsh

# asumes zsh and java is installed (openjdk-11-jdk works)
# download antlr-4.9.3-complete.jar from https://github.com/antlr/website-antlr4/tree/gh-pages/download and put in /usr/local/lib/
# change directory to this folder and run ./generate.sh
rm -r autogenerated/*.cc
java -Xmx500M -cp "/usr/local/lib/antlr-4.9.3-complete.jar:$CLASSPATH" org.antlr.v4.Tool -Dlanguage=Cpp MDBLexer.g4 -o autogenerated -no-listener -visitor
java -Xmx500M -cp "/usr/local/lib/antlr-4.9.3-complete.jar:$CLASSPATH" org.antlr.v4.Tool -Dlanguage=Cpp MDBParser.g4 -o autogenerated -no-listener -visitor
autoload zmv
zmv 'autogenerated/(*).cpp' autogenerated/'$1.cc'
